# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

def pods
    pod 'NMapsMap'
    pod 'Google-Mobile-Ads-SDK'
end

target 'StreetDrop' do
    pods
end

target 'ShareExtension' do
    pods
end
